---
title: "BS 1515 Lecture 3: Derivatives and Integrals"
author: "Sergey V. Popov"
date: "`r Sys.Date()`"
output: slidy_presentation
css: cardiff.css

header-includes:
  - \usepackage{nicefrac}
  - \usepackage{tikz}
  - \usetikzlibrary{patterns}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Last time

We defined

- sets: collection of things
- spaces: set of "everything"
- functions: rule of going from one set to another
- ordering: function from set-squared to $\{0,1\}$
- metric: function from set-squared to $\mathbb{R}_{+}$
- (in)equalities: implicitly defined sets
- systems of (in)equalities: intersection of implicitly defined sets

Today

- functions of $\mathbb{R}\rightarrow \mathbb{R}$
- derivatives
- integrals

## Functions

Any rule that assigns an element of *domain* set to the element of *codomain* set.

- Examples: $y(x)=x^2$; metric; preference.
- Graph: $g(x,y)=1$ iff $y=f(x)$ means g(x,y) is the graph of $f(x)$. Subgraph: everything below the graph. Supergraph: everything above the graph.
- If you have multiple values for the same *argument*, this is *correspondence*, not a function!
- If you don't have a value for a certain argument, the function is *not well-defined*.

## Example

Demand: $Q(p):\mathbb{R}_{+}\rightarrow \mathbb{R}_{+}$.

Inverse demand: $P(q)=Q^{-1}(p)=\{p:Q(p)=q\}$.

Total revenue: $TR(q)=q \cdot P(q)$.

Total cost: $TC(q)=F+VC(q):\mathbb{R}_{+}\rightarrow \mathbb{R}_{+}$.

Profit: $\Pi(q)=TR(q)-TC(q)$.

How would we choose output?..

## What Kind of Functions Are There

*Continuous*: a small change, left or right, does not change the value much.

*Monotone*: an increase in argument leads to an increase in the result, same as *increasing*. *Monotone decreasing* is opposite.

*Weakly* monotone: $x_1>x_2 \Rightarrow f(x_1)\geq f(x_2)$.

Demand: probably decreasing? If not monotone decreasing, hard to invert.

Continuous? Maybe...

Total cost: probably increasing?..

## Plot Functions

```{tikz,fig.alt="Choosing a point by pointing at the graph", fig.ext='png'}

\centering \begin{tikzpicture}[x=1.6cm,y=1.6cm]
\draw[->] (0,0)--(4.1,0) node[right] {$q$};
\draw[->] (0,0)--(0,4.1) node[above] {$TR,TC$};
\foreach \x in {1,...,4}
\draw[] (\x,0.1)--(\x,-0.1) node[below] {$\x$};
\foreach \x in {1,...,4}
\draw[] (-0.1,\x)--(0.1,\x) node[right] {$\x$};
\begin{scope}
  \clip (0,0) rectangle (4.5,4.5);
  \draw[ultra thick, color=blue] plot[domain=0:4,smooth] ({\x},{\x*(4-\x)}) node[above right] {$TR$};
  \draw[ultra thick, color=green!40!black] plot[domain=0:4,smooth] ({\x},{0.25*\x*\x}) node[left] {$TC$};
\end{scope}
\end{tikzpicture}
```

## Calculus

*Infinitesimal calculus* is about studying small changes. Differential calculus: study what changes if we have a small change in the argument. Integral calculus: how do these changes accumulate.

*Derivative* of a function is the slope of the function.

*Integral* of a function is the area of the function's subgraph above zero (can be negative if the graph is below zero!)

Based on the concept of *limit*. A set of points $\{a_i\}$ is a *sequence* if
- $i\in \{1,2,...\}$ 
- order matters.

Sequences might have limit points. $A$ is a *limit point* of $\{a_i\}$ if $B_\varepsilon(A)$ contains an infinity of points of $\{a_i\}$ for all $\varepsilon$.

Point $A$ is a *limit* of $\{a_i\}$ if $\neg B_\varepsilon(A) \bigcap \{a_i\}$ is finite for all $\varepsilon$.

A sequence is decreasing if $a_{i+1}\leq a_i$.

## Limit Exercises

Prove: a decreasing bounded sequence has a limit.

Prove: an increasing bounded sequence has a limit.

Prove: $\{1,0,1,0,1,0,...\}$ does not have a limit.

Prove: $\left\{\frac{1}{1},\frac{1}{2},\frac{1}{3},..\right\}$ has a limit.

Useful to know:

- $\lim (a_n+b_n)=\lim a_n+\lim b_n$ as long as all are well defined

- $\lim c\cdot a_n=c\cdot \lim a_n$

Prove: if $f()$ is continuous, $\lim f(a_n)=f(\lim a_n)$: continuous functions preserve convergence.

## Derivative

\[f'(x)=\lim_{\Delta\rightarrow 0} \frac{f(x+\Delta)-f(x)}{\Delta}\]

- as $\Delta\rightarrow 0$: take every $\Delta_n \rightarrow 0$
- your $\frac{f(x+\Delta_n)-f(x)}{\Delta_n}$ must have the same limit, denoted by $f'(x)$.

Example: $f(x)=x$ - what's the limit?

What about $f(x)=x^2$?

What about $f(x)=x^3$?

Prove: There is no derivative for $f(x)=|x|$ at $x=0$.

Prove: $(\sqrt{x})'=\frac{1}{2}\frac{1}{\sqrt{x}}$ using the definition of the derivative (not the power formula).

## Product of functions

Imagine you know $f'(x)$ and $g'(x)$ and you need to find the derivative of $f(x)g(x)$.

\[\left(f(x)g(x)\right)'=f'(x)g(x)+g'(x)f(x)\]

Prove: You know $x'=1$ and $(x^{n})'=nx^{n-1}$ for integer $n\geq 2$. Prove that $(x^{n+1})'=(n+1)x^{n}$.

Prove: $(f(x)g(x)h(x))'=f'(x)g(x)h(x)+f(x)g'(x)h(x)+f(x)g(x)h'(x)$.

Note that if you take $g(x)=1/f(x)$, you have $f(x)g(x)=1$.

Prove: $(1/f(x))'=\frac{-f'(x)}{(f(x))^2}$.

## Composition of functions

Imagine you have $g(f(x))$, and you know $f'(x)$ and $g'(y)$. Then

\[\left(g(f(x)) \right)'=g'(f(x))f'(x).\]

Prove: $\left(\frac{1}{f(x)}\right)'=-\frac{1}{(f(x))^2}f'(x)$

Prove: $\left(\frac{g(x)}{f(x)}\right)'=\frac{f'(x)g(x)-g(x)f'(x)}{(f(x))^2}$

Remember: $g(y)$ is an inverse of $y=f(x)$ if $g(f(x))=x$.

Prove: $g'(y)=\frac{1}{f'(g(y))}$.

Prove: $(\sqrt{x})'=\frac{1}{2}\frac{1}{\sqrt{x}}$.

Prove: $(e^x)'=e^x$ knowing $e=\lim_{t\rightarrow 0} \left(1+t\right)^{1/t}$.

Prove: $(a^x)'=\ln a\cdot a^x$.

Prove: $(\ln x)'=1/x$.

## Example

\[TR(q)=q\cdot (4-q), TC(q)=q^2/4 \Rightarrow \Pi(q)=4q-q^2-q^2/4.\]

Imagine you are in the optimal point. What should be the derivative of the profit? Zero!

- If it is positive, produce a bit more, increase profits!
- If it is negative, produce a bit less, increase profits!

$\Pi'(q)=4-q^* 5/2=0$ so $q^*=8/5.$

We will expand on optimization next week.

## Implicit Function Theorem

If $f(x,y)=0$ can't be solved for an analytical solution, as long as $f'_y(x,y)$ is not zero and derivatives are continuous, there is a local $\phi(x)$ such that $f(x,\phi(x))=0$ and $y^*=\phi(x^*$ in the neighborhood of $(x^*,y^*)$.

Example: let $f(x,y)=\sqrt{x^2+y^2}-1$. Then there are two solutions at $x^*=1/2$, one is $y^*=\frac{\sqrt{3}}{2}$ and another at $y^*=\frac{-\sqrt{3}}{2}$, so there is no *function* that would tell what happens to the solution if we change $x$. But there is a function near $(1/2,\sqrt{3}/2)$ and another near $(1/2,-\sqrt{3}/2)$.

For such a $\phi(x)$, it should work that $f(x,\phi(x))=0$. Take a derivative with respect to $x$ of both sides:
\[f'_x(x,\phi(x))+f'_y(x,\phi(x))\phi'(x)=0,\]
so $\phi'(x)=-\frac{f'_x(x,\phi(x))}{f'_y(x,\phi(x))}.$ Since the right-hand side is continuous, this differential equation has a solution.

## Integrals

Differentiation is going from $F(x)$ to the *local change* $f(x)=F'(x)$. Integration is going from local change to total, from $f(x)$ to $F(x)$ such that $F'(x)=f(x)$.

Example: speed as a function of time. Derivative is acceleration; integral is distance traveled.

*Indefinite* integral is $\int f(x) dx$: defined up to a constant. *Definite* integral has limits: $\int_a^b f(x) dx$. *Improper* might have an infinity on one of the sides.

Example: if $MC(q)=a+bq$, $TC(q)=aq+b/2 q^2+c$ --- fixed costs are impossible to deduce from MC!

## Rules for integrals

\[\int \left(af(x)+bg(x)\right) dx = a \int f(x) dx+b \int g(x) dx,\]

\[\int x^n dx=\frac{1}{n+1} x^{n+1}+C, n\not =-1.\]

\[\int 1/x dx=ln x +C.\]

\[\int e^x dx=e^x +C.\]

\[\int a^x dx=\frac{1}{\ln a}a^x +C.\]

## Integration by Substitution

\[ \int e^x \sqrt{3e^x+2} dx \]

looks scary? but note $(3e^x+2)'=3e^x$. So let $y=3e^x+2$ then $dy=3e^x dx$ and the integral can be rewritten as

\[\int \frac{1}{3} \sqrt{y} dy\]

which is much easier.

## Integration by Parts

Observe that \[(u(x)v(x))'=u'(x)v(x)+v'(x)u(x)\]

so if you have to find $\int u'(x)v(x) dx$ you can use
\[ \int u'(x)v(x) dx=u(x)v(x)+C- \int v'(x) u(x) dx \]

Example:

\[\int \frac{ln (x)}{x^2}dx\]

Observe that $\ln'(x)=1/x$ so let $u'(x)=\frac{1}{x^2}$ and $v(x)=\ln(x)$, then
\[u(x)=-1/x, v'(x)=1/x\]
and
\[\int \frac{\ln (x)}{x^2}dx=\ln(x)\frac{-1}{x}+C-\int \frac{-1}{x}\frac{1}{x}=-\frac{\ln (x)+1}{x}+C\]

## Examples

Consider a sphere of radius $R$. What is the volume of this sphere?

Answer: if we slice it by circles, each circle has an area of $\pi r^2$ for some r. What kind of $r$s do we see? Draw the sphere around $0$, take $x\in [-R,R]$. Take the set $\{(x,y,z)|x=x_0\}$; it's a circle of radius $r=\sqrt{R^2-x_0^2}$. Let us add these circles together as a function of x:
\[\int_{-R}^R \pi (R^2-x^2) dx\]
The indefinite integral is $\pi (R^2 x-x^3/3)+C$; taken from $-R$ to $R$ you get
\[\pi (\frac{2}{3}R^3-(-\frac{2}{3}R^3))=\frac{4}{3}\pi R^3.\]

## Useful Ideas

Continuous functions on an interval are integrable.

\[\int_a^b f(x) dx= F(b)-F(a).\]

\[\left(\int_a^b f(x) dx\right)'_b=F'(b)=f(b).\]

\[\left(\int_a^b f(x) dx\right)'_a=-F'(a)=-f(a).\]

\[\left(\int_a^b f(t,x) dx\right)'_a=\int_a^b f'_t(t,x)dx.\]

All of these need technical assumptions but if (a) your functions are continuous and (b) you are on an interval, you should be fine.



## Summary for Today

- Derivatives: an increase in a function

- Integrals: a sum over values of the function

- We will be using them for things