---
title: "Problem Set 4: Optimization"
author: "Sergey V. Popov"
date: "`r Sys.Date()`"
output: html_document
css: cardiff.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Optimization

Model these problems as single-function optimization problems and solve:

- You have 50 meters of fence. What rectangle maximizes the area that can be fenced with it?
- We are designing a closed cylindrical can to hold 1 liter of liquid. What shape minimizes the amount of material (total surface area, including top and bottom)?
- You have a rectangle of size $A$ by $B$. You want to cut out four $x \times x$ squares from the corners and fold the sides up to make a box without a top. What $x\in[0,\min(A,B)/2]$ maximizes the volume?
    + It might help to first establish that $(A+B)^2\geq 3AB$.
     + Would you have a corner solution?      
     + How do you choose between the two candidates for the maximum?

## Convexity

Taking the second derivative, find out where these functions are convex or concave:

- $f(x)=ax^3+bx^2+cx+d$
- $f(x)=\ln(ax^2+bx+c)$ (you might first need to establish where it is well defined)
- $f(x)=e^{ax^2+bx+c}$

## Higher Order Derivatives

Take $f(x)=-(x-4)^4$. The only extremum point is $x^*=4$. Using higher-order derivatives (the second one would not be enough!), verify that this is a maximum.

## Integrals

For functions (you will recognize them as *densities* in the second half of BS1515) with $a>0$ and $\alpha>0$:

a. $f(x)=1/a$ for $x\in[0,a]$ and $0$ otherwise;
b. $f(x)=6x(1-x)$ for $x \in [0,1]$ and $0$ otherwise;
c. $f(x)=2x/a^2$ for $x \in [0,a]$ and $0$ otherwise;
d. $f(x)=\alpha e^{-\alpha x}$ for $x \in \mathbb{R}_+$ and $0$ otherwise,

plot them and calculate

- the definite integral: $\int_{-\infty}^{+\infty} f(x) dx$ (note that space where $f(x)=0$ can be dropped); it should be 1 for each function
- $E[x]=\int_{-\infty}^{+\infty} x f(x) dx$ (you will recognize them as *expectations* in the second half of BS1515)
- $E[x^2]=\int_{-\infty}^{+\infty} x^2 f(x) dx$
